[general]
    description = "22 Test for diktat - linter and formatter for Kotlin"
    language = "Kotlin"
    # this is the default value, you don't need to add it explicitly, but can be useful, if you have different pattern:
    expectedWarningsPattern = "// ;warn:?(.*):(\\d*): (.+)"
    timeOutMillis = 30000

