[general]
    tags = ["tag1"]
    description = "Chapter 4 tests: with multilines warning"
    suiteName = "Directory: Chapter4"
    expectedWarningsPattern = "/\\* ;warn:?(.*):(\\d*): (.+)"
    expectedWarningsMiddlePattern = "\\* (.*)"
    expectedWarningsEndPattern = "(.*)?\\*/"

[warn]
    lineCaptureGroup = 1
    columnCaptureGroup = 2
    messageCaptureGroup = 3
