[general]
tags = ["fix and warn"]
description = "Autofixing of issues discovered by diKTat on smoke tests and warn about issues, which couldn't be auto-corrected"
suiteName = "Autofix and Warn"

["fix and warn"]
    ["fix and warn".fix]
        execFlags = "-F"
    ["fix and warn".warn]
        actualWarningsPattern = "(\\w+\\..+):(\\d+):(\\d+): (\\[.*\\].*)$"
