[general]
exec_cmd="./ktlint -R diktat-0.4.2.jar"
description = "My suite description"
suiteName = "DocsCheck"

[diff]
exec_flags="-F"
testFilePattern="*Test.kt"
expectedFilePattern="*Expected.kt"
batchMode = false
