[general]
description = "My suite description"
suiteName = "DocsCheck"

[fix]
execCmd="./ktlint -R diktat-0.4.2.jar -F"
testFilePattern="*Test.kt"
expectedFilePattern="*Expected.kt"
batchMode = false
