[general]
exec_cmd=""
description = "My suite description"
suiteName = "DocsCheck"

[diff]
exec_flags="./ktlint -R diktat-0.4.2.jar -F"
testFilePattern="*Test.kt"
expectedFilePattern="*Expected.kt"
batchMode = false
