[general]
exec_cmd="./ktlint -R diktat-0.4.2.jar"
tags = "mytags"
description = "My suite description"
suiteName = "DocsCheck"

[fix]
exec_flags="-F"
testFilePattern="*Test.kt"
expectedFilePattern="*Expected.kt"
