[general]
tags = "tag1"
description = "chapter 2 tests: with default lines (no line numbers)"
suiteName = "Chapter2"
expectedWarningsPattern = "// ;warn:(\\d*):(\\d*): (.+)"

[warn]
lineCaptureGroup = 1
columnCaptureGroup = 2
messageCaptureGroup = 3
