[general]
description = "My suite description"
suiteName = "DocsCheck"

[diff]
exec_cmd="./ktlint -R diktat-0.4.2.jar -F"
testFilePattern="*Test.kt"
expectedFilePattern="*Expected.kt"
output = "stdout" # you can also use 'inPlace' here to do fixes right into the test file (test files won't be broken or changed)
batchMode = false
