[general]
    tags = ["tag2"]
    description = "Test suite that check only raised warnings related to general coding practices in files detected by a keyword."

[warn]
    testNameRegex = "^E.*T.*D.*"
