[general]
execCmd = "./detekt"
tags = ["test"]
description = "Root test directory"
suiteName = "DocsCheck"

[warn]
execFlags = "--build-upon-default-config -i"
actualWarningsPattern = "\\w+ - (\\d+)/(\\d+) - (.*)$"  # e.g. `WARN - 10/14 - Class name is in incorrect case`
lineCaptureGroup = 1  # index of regex capture group for line number, used when `warningTextHasLine: false`
columnCaptureGroup = 2  # index of regex capture group for column number, used when `warningTextHasColumn: false`
messageCaptureGroup = 3  # index of regex capture group for message text
warningTextHasColumn = true
warningTextHasLine = true