[general]
tags = warn
description = "Test warnings discovered by diKTat"
suiteName = "warnings"
ignoreSaveComments = true

[warn]
execFlags = --debug  # todo: replace with empty string once ktoml supports quotes
warningsInputPattern=.*// ;warn:(\d+):(\d+) (.*)
warningsOutputPattern=(\w+\..+):(\d+):(\d+): (.*)$
lineCaptureGroup = 1
columnCaptureGroup = 2
messageCaptureGroup = 3
fileNameCaptureGroupOut = 1
lineCaptureGroupOut = 2
columnCaptureGroupOut = 3
messageCaptureGroupOut = 4
exactWarningsMatch = true
warningTextHasColumn = true
warningTextHasLine = true
