[general]
    tags = ["warn"]
    description = "Test warnings discovered by diKTat"
    suiteName = "Autofix and Warn"

[warn]
    # suffix to detect tests
    testNameSuffix = "Test.kt"
    wildCardInDirectoryMode = "**/*"
    # diktat warnings have the following format: filename.kt:1:15: [WARN_NAME] my waring
    actualWarningsPattern="(\\w+\\..+):(\\d+):(\\d+): (\\[.*\\].*)"
    lineCaptureGroup = 1
    columnCaptureGroup = 2
    messageCaptureGroup = 3
    fileNameCaptureGroupOut = 1
    lineCaptureGroupOut = 2
    columnCaptureGroupOut = 3
    messageCaptureGroupOut = 4
    exactWarningsMatch = false
    warningTextHasColumn = true
    warningTextHasLine = true
