[general]
tags = "warn"
description = "Test warnings discovered by diKTat"
suiteName = "warnings"
ignoreSaveComments = true

[warn]
warningsInputPattern=".*// ;warn:(\d+):(\d+) (.*)"
warningsOutputPattern="(\w+\..+):(\d+):(\d+): (.*)$"
lineCaptureGroup = 1
columnCaptureGroup = 2
messageCaptureGroup = 3
fileNameCaptureGroupOut = 1
lineCaptureGroupOut = 2
columnCaptureGroupOut = 3
messageCaptureGroupOut = 4
exactWarningsMatch = false
warningTextHasColumn = true
warningTextHasLine = true
