[general]
tags = warn
description = "Test warnings discovered by diKTat"
suiteName = "warnings"

[warn]
execFlags = --debug  # todo: replace with empty string once ktoml supports quotes
warningsInputPattern = "// ;warn:(\\d+):(\\d+): (.*)"
warningsOutputPattern = "\\w+ - (\\d+)/(\\d+) - (.*)$"
lineCaptureGroup = 1
columnCaptureGroup = 2
messageCaptureGroup = 3
warningTextHasColumn = true
warningTextHasLine = true
