[general]
    tags = ["warn", "sarif"]
    description = "Test warnings discovered by diKTat, reading expected warnings from SARIF file"
    suiteName = "Only Warnings: with SARIF format"
    expectedWarningsPattern = "// ;warn:?(.*):(\\d+):? ?(.+)?"
    execCmd = "java -Dlogback.configurationFile=logback.xml -jar ktlint --disabled_rules=standard -R diktat.jar"

[warn]
    execFlags = "--reporter=sarif"
    # regular expression to detect tests
    testNameRegex = ".*Test.kt"
    actualWarningsFormat = "SARIF"
    # by default, in SARIF mode, it's supposed, that tool will print sarif report into the stdout
    # however, it also could be provided via file
    # actualWarningsFileName = "save-warnings-actual.sarif"
    fileNameCaptureGroupOut = 1
    lineCaptureGroupOut = 2
    columnCaptureGroupOut = 3
    messageCaptureGroupOut = 4
    exactWarningsMatch = false
    warningTextHasColumn = true
    warningTextHasLine = true