[general]
tags = "tag1"
description = "My suite description"
suiteName = "DocsCheck"

[warn]
execCmd = "./detekt --build-upon-default-config -i"
warningsInputPattern = "// ;warn:(\\d+):(\\d+): (.*)"
warningsOutputPattern = "\\w+ - (\\d+)/(\\d+) - (.*)$"
lineCaptureGroup = 1
columnCaptureGroup = 2
messageCaptureGroup = 3
warningTextHasColumn = true
warningTextHasLine = true

[fix]
execCmd="./ktlint -R diktat-0.4.2.jar -F"
