[general]
execCmd = "./detekt"
tags = ["tag1"]
description = "Test suite"
suiteName = "DocsCheck"
expectedWarningsPattern = "// ;warn:(\\d+):(\\d+): (.*)"

[warn]
execFlags = "--build-upon-default-config -i"
actualWarningsPattern = "\\w+ - (\\d+)/(\\d+) - (.*)$"
lineCaptureGroup = 1
columnCaptureGroup = 2
messageCaptureGroup = 3
warningTextHasColumn = true
warningTextHasLine = true

[fix]
execFlags="-p"
resourceNameTestSuffix="Test"
resourceNameExpectedSuffix="Expected"
