[general]
execCmd = "./detekt"
tags = tag1
description = "My suite description"
suiteName = "DocsCheck"

[warn]
execFlags = "--build-upon-default-config -i"
warningsInputPattern = "// ;warn:(\\d+):(\\d+): (.*)"
warningsOutputPattern = "\\w+ - (\\d+)/(\\d+) - (.*)$"
lineCaptureGroup = 1
columnCaptureGroup = 2
messageCaptureGroup = 3
warningTextHasColumn = true
warningTextHasLine = true

[fix]
execFlags="-p"
resourceNameTestSuffix="Test"
resourceNameExpectedSuffix="Expected"
# testFilePattern="*Test.kt"
# expectedFilePattern="*Expected.kt"