name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build_and_test_with_code_coverage:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v2
      # ensure that gradle wrapper files in repository are valid by checking checksums
      - uses: gradle/wrapper-validation-action@v1
      - if: ${{ runner.os == 'Windows' }}
        name: Install curl on Windows
        run: |
          choco install curl
          curl --version
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan
          restore-keys: |
            ${{ runner.os }}-gradle-konan
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
          # Note: https://github.com/burrunan/gradle-cache-action/issues/42 can possible break this
          arguments: |
            build
            -PdisableRedundantTargets
            -x detekt
            -x linkReleaseExecutableLinuxX64
            -x linkReleaseExecutableMingwX64
            -x linkReleaseExecutableMacosX64
          properties: |
            org.gradle.caching=true
            detekt.multiplatform.disabled=true
      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: gradle-reports-${{ matrix.os }}
          path: '**/build/reports/'
      - name: Code coverage report
        #if: ${{ runner.os == 'Linux' }}
        if: ${{ false }}
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true # optional (default = false)
