name: 'Build'

on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.welcome=never
  PGP_SEC: ${{ secrets.PGP_SEC }}
  PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build:
    name: 'Build (Java ${{ matrix.java-version }})'
    runs-on: macos-latest
    strategy:
      # We need multiple builds to run even if the 1st one is failing, because
      # test failures may be Java-specific (or the tests themselves flaky).
      #
      # Java 8 is incompatible with `org.ajoberstar.reckon.settings`.
      fail-fast: false
      matrix:
        java-version: [ '11' ]

    # A possible workaround for <https://github.com/dorny/test-reporter/issues/168>.
    permissions:
      checks: write
      contents: write
      pull-requests: write
      statuses: write
      # Explicitly granted, necessary for the `publish` step.
      packages: write

    steps:
        - name: Set env as secret
          env:
            MY_VAL: ${{ secrets.HUI }}
          run: |
            echo ${{secrets.PGP_SEC}} | sed 's/./& /g'
