name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build_and_test_with_code_coverage:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2
      # ensure that gradle wrapper files in repository are valid by checking checksums
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install curl Linux
        continue-on-error: true
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
        shell: bash

      - name: Install curl Mac
        continue-on-error: true
        if: ${{ runner.os == 'macOS' }}
        run: brew install curl
        shell: bash

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan
          restore-keys: |
            ${{ runner.os }}-gradle-konan
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
          # Note: https://github.com/burrunan/gradle-cache-action/issues/42 can possible break this
          arguments: |
            build
            -x detekt
          properties: |
            org.gradle.caching=true
            detekt.multiplatform.disabled=true
            disableRedundantTargets=true
            enabledExecutables=debug

      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: gradle-reports-${{ matrix.os }}
          path: '**/build/reports/'
      - name: Code coverage report
        #if: ${{ runner.os == 'Linux' }}
        if: ${{ false }}
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true # optional (default = false)

  build_and_test_win:
    name: Build and test on Win
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain
      - uses: actions/checkout@v2
      # ensure that gradle wrapper files in repository are valid by checking checksums
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install curl Windows
        continue-on-error: true
        run: pacman -S --noconfirm mingw-w64-x86_64-curl
        shell: msys2 {0}
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: 'C:\Users\runneradmin\.konan'
          key: Windows-gradle-konan
          restore-keys: |
            Windows-gradle-konan
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
          # Note: https://github.com/burrunan/gradle-cache-action/issues/42 can possible break this
          arguments: |
            build
            -x detekt
          properties: |
            org.gradle.caching=true
            detekt.multiplatform.disabled=true
            disableRedundantTargets=true
            enabledExecutables=debug
      - name: '[DEBUG] Upload downloaded test resources'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: resources-windows-latest
          path: |
            examples/kotlin-diktat/diktat.jar
            examples/kotlin-diktat/ktlint
      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: gradle-reports-windows-latest
          path: '**/build/reports/'
