name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build_and_test_with_code_coverage:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan
          restore-keys: |
            ${{ runner.os }}-gradle-konan
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
          # Note: https://github.com/burrunan/gradle-cache-action/issues/42 can possible break this
          arguments: |
            build
            -x detekt
          properties: |
            org.gradle.caching=true
            detekt.multiplatform.disabled=true
            disableRedundantTargets=true
            enabledExecutables=debug

      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: gradle-reports-${{ matrix.os }}
          path: '**/build/reports/'
      - name: Code coverage report
        #if: ${{ runner.os == 'Linux' }}
        if: ${{ false }}
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
          fail_ci_if_error: true # optional (default = false)

  build_and_test_win:
    name: Build and test on Win
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: 'C:\Users\runneradmin\.konan'
          key: Windows-gradle-konan
          restore-keys: |
            Windows-gradle-konan
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
          # Note: https://github.com/burrunan/gradle-cache-action/issues/42 can possibly break this
          arguments: |
            build
            -x detekt
          properties: |
            org.gradle.caching=true
            detekt.multiplatform.disabled=true
            disableRedundantTargets=true
            enabledExecutables=debug
      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: gradle-reports-windows-latest
          path: '**/build/reports/'
          retention-days: 1
