name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build_and_test_with_code_coverage:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Cache konan
        uses: actions/cache@v3
        with:
          # [@actions/glob](https://github.com/actions/toolkit/tree/main/packages/glob) is used to match paths
          # It should correctly expand `~` on every OS.
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan-1.7.0
          restore-keys: |
            ${{ runner.os }}-gradle-konan-1.7.0
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: |
            build
            -x detekt
            -Porg.gradle.caching=true
            -Pdetekt.multiplatform.disabled=true
            -PdisableRedundantTargets=true
            -PenabledExecutables=debug
            -PgprUser=${{ github.actor }}
            -PgprKey=${{ secrets.GITHUB_TOKEN }}

      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: gradle-reports-${{ matrix.os }}
          path: '**/build/reports/'
      - name: Code coverage report
        if: ${{ runner.os == 'Linux' }}
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: false # optional (default = false)
