name: Create release

on:
  push:
    tags:
      - 'v*'
#env:
  #GPG_SEC: ${{ secrets.PGP_SEC }}
  #GPG_PASSWORD: ${{ secrets.PGP_PASSWORD }}
  #OSSRH_USERNAME: ${{ secrets.SONATYPE_USER }}
  #OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  release:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ] #, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: burrunan/gradle-cache-action@v1
        name: Gradle release with caches caching
        with:
          #arguments: linkReleaseExecutableMultiplatform publishToSonatype closeAndReleaseSonatypeStagingRepository
          arguments: linkReleaseExecutableMultiplatform
          gradle-version: wrapper
      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: save-cli-${{ runner.os }}
          path: save-cli/build/bin/**/releaseExecutable/*


  github_release:

    needs: release
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          path: tmpFolder

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Assets
        working-directory: ./tmpFolder
        run: ls -l

      - name: Assets 2
        working-directory: ./tmpFolder/save-cli-Linux
        run: ls -l

      - name: Assets 3
        working-directory: ./tmpFolder/save-cli-Windows
        run: ls -l

      - name: Upload save-cli
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmpFolder/**/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
